name: retail
description: "pos app"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  adaptive_theme: ^3.6.0
  collection: ^1.18.0
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.8
  skeletonizer: ^1.4.2
  dio: ^5.7.0
  get_it: ^8.0.1
  go_router: ^14.3.0
  responsive_framework: ^1.5.1
  flex_color_scheme: ^7.3.1
  cached_network_image: ^3.4.1
  dio_http2_adapter: ^2.5.3
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.2
  equatable: ^2.0.5
  flutter_keyboard_visibility: ^6.0.0
  flutter_bloc: ^8.1.6
  lottie: ^3.1.3
  auto_size_text: ^3.0.0
  page_transition: ^2.1.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.0.0
  animate_do: ^3.3.4
  pinput: ^5.0.0
  device_preview:
  awesome_dialog: ^3.2.1
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_multi_select_items: ^0.4.3
  bloc_concurrency: ^0.2.5
  uuid: ^4.5.1
  carousel_slider: ^5.0.0
  animated_float_action_button: ^1.0.4
  syncfusion_flutter_datagrid: ^28.1.41
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.5
  usb_serial: ^0.5.2
  printer_service: ^2.0.3
  image: 
  screenshot: ^3.0.0
  dotted_line: ^3.2.3
  flutter_barcode_listener: ^0.1.4
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^6.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/
  fonts:
    - family: NeoSansArabic
      fonts:
        - asset: assets/fonts/NeoSansArabic.ttf
